//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//

Utilisateur = function(args) {
  this.pseudo = null;
  this.motdepasse = null;
  if (args) {
    if (args.pseudo !== undefined) {
      this.pseudo = args.pseudo;
    }
    if (args.motdepasse !== undefined) {
      this.motdepasse = args.motdepasse;
    }
  }
};
Utilisateur.prototype = {};
Utilisateur.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.pseudo = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRING) {
        this.motdepasse = input.readString().value;
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Utilisateur.prototype.write = function(output) {
  output.writeStructBegin('Utilisateur');
  if (this.pseudo) {
    output.writeFieldBegin('pseudo', Thrift.Type.STRING, 1);
    output.writeString(this.pseudo);
    output.writeFieldEnd();
  }
  if (this.motdepasse) {
    output.writeFieldBegin('motdepasse', Thrift.Type.STRING, 2);
    output.writeString(this.motdepasse);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

